exclude = [
  "*.ipynb",
  "*playground*",
  "README.md",
  "old/",
]

[lint]
ignore = [
  # line too long
  "E501", 
  # module level import not at top of file
  "E402", 
  # ambiguous variable name
  "E741",
  # local variable name is assigned to but never used
  "F841", 
  # import star
  "F403",
  # undefined or defined from star imports
  "F405",
  # unused imports
  "F401",
  # multiple statements on one line
  "E701",
  # bare except
  "E722",
]
